auth_login_homepage:
    pattern:  /login
    defaults: { _controller: AuthLoginBundle:Default:index }

auth_login_signup:
    pattern:  /signup
    defaults: { _controller: AuthLoginBundle:Default:signup }
